version: 2

sources:

  - name: projectrawdata
    description: "Source BigQuery regroupant données musicales, concerts, artistes et boxscores."
    tables:
      - name: box_scores_all
        identifier: "box_scores_all"
        description: "Boxscores complets tous artistes."
